SET NAMES UTF8;

INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '1', 'Guatemala' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='1' OR UPPER(d.nombre)=UPPER('Guatemala'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '2', 'El Progreso' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='2' OR UPPER(d.nombre)=UPPER('El Progreso'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '3', 'Sacatepéquez' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='3' OR UPPER(d.nombre)=UPPER('Sacatepéquez'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '4', 'Chimaltenango' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='4' OR UPPER(d.nombre)=UPPER('Chimaltenango'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '5', 'Escuintla' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='5' OR UPPER(d.nombre)=UPPER('Escuintla'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '6', 'Santa Rosa' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='6' OR UPPER(d.nombre)=UPPER('Santa Rosa'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '7', 'Sololá' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='7' OR UPPER(d.nombre)=UPPER('Sololá'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '8', 'Totonicapán' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='8' OR UPPER(d.nombre)=UPPER('Totonicapán'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '9', 'Quetzaltenango' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='9' OR UPPER(d.nombre)=UPPER('Quetzaltenango'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '10', 'Suchitepéquez' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='10' OR UPPER(d.nombre)=UPPER('Suchitepéquez'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '11', 'Retalhuleu' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='11' OR UPPER(d.nombre)=UPPER('Retalhuleu'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '12', 'San Marcos' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='12' OR UPPER(d.nombre)=UPPER('San Marcos'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '13', 'Huehuetenango' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='13' OR UPPER(d.nombre)=UPPER('Huehuetenango'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '14', 'Quiché' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='14' OR UPPER(d.nombre)=UPPER('Quiché'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '15', 'Baja Verapaz' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='15' OR UPPER(d.nombre)=UPPER('Baja Verapaz'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '16', 'Alta Verapaz' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='16' OR UPPER(d.nombre)=UPPER('Alta Verapaz'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '17', 'Petén' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='17' OR UPPER(d.nombre)=UPPER('Petén'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '18', 'Izabal' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='18' OR UPPER(d.nombre)=UPPER('Izabal'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '19', 'Zacapa' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='19' OR UPPER(d.nombre)=UPPER('Zacapa'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '20', 'Chiquimula' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='20' OR UPPER(d.nombre)=UPPER('Chiquimula'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '21', 'Jalapa' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='21' OR UPPER(d.nombre)=UPPER('Jalapa'));
INSERT INTO departamento (id_pais, codigo, nombre) SELECT p.id_pais, '22', 'Jutiapa' FROM pais p WHERE UPPER(p.nombre)=UPPER('Guatemala') AND NOT EXISTS (SELECT 1 FROM departamento d WHERE d.codigo='22' OR UPPER(d.nombre)=UPPER('Jutiapa'));

COMMIT;
