SET NAMES UTF8;

INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Analfabeta', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Analfabeta'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Bachillerato', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Bachillerato'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Carrera comercial', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Carrera comercial'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Carrera técnica', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Carrera técnica'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Cuarto de primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Cuarto de primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'De cuarto a sexto primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('De cuarto a sexto primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'De primero a tercero primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('De primero a tercero primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Diplomado', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Diplomado'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Doctorado', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Doctorado'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Especialidad técnica', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Especialidad técnica'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Estudiante', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Estudiante'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Licenciatura', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Licenciatura'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Maestra de educación para el hogar', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Maestra de educación para el hogar'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Maestra de educación primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Maestra de educación primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Maestra de párvulos', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Maestra de párvulos'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Maestro de educación primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Maestro de educación primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Maestría', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Maestría'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Magisterio', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Magisterio'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Magisterio bilingüe', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Magisterio bilingüe'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Nivel básico', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Nivel básico'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Nivel diversificado', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Nivel diversificado'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Nivel medio', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Nivel medio'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Nivel post-grado', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Nivel post-grado'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Nivel universitario', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Nivel universitario'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Nivel universitario licenciatura', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Nivel universitario licenciatura'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Nivel universitario técnico', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Nivel universitario técnico'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'No registrado', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('No registrado'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Pasante', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Pasante'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Pensum cerrado', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Pensum cerrado'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Perito contador', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Perito contador'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Preprimaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Preprimaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Primero básico', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Primero básico'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Primero primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Primero primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Quinto de primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Quinto de primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Sabe leer y escribir', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Sabe leer y escribir'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Secretaria bilingüe', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Secretaria bilingüe'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Secretaria comercial', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Secretaria comercial'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Segundo básico', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Segundo básico'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Segundo de primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Segundo de primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Sexto de primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Sexto de primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Tercero básico', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Tercero básico'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Tercero de primaria', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Tercero de primaria'));
INSERT INTO nivel_escolaridad (nombre, orden) SELECT 'Vocacional', NULL FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM nivel_escolaridad WHERE UPPER(nombre)=UPPER('Vocacional'));

COMMIT;
