SET NAMES UTF8;

INSERT INTO tipo_atencion (nombre, descripcion) SELECT 'LEGAL/VICTIMOLÓGICO', 'Fuente Atenciones IV 2020-2023' FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM tipo_atencion WHERE UPPER(TRIM(nombre)) = UPPER('LEGAL/VICTIMOLÓGICO'));

COMMIT;