SET NAMES UTF8;

INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-001' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-002' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-003' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-004' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-005' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-006' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-007' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-008' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-009' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-010' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-011' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-012' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-013' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-014' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-015' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-016' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-017' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-018' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-019' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-020' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-021' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-022' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'NEC-DEL-023' AND UPPER(TRIM(c.nombre)) = UPPER('Causa de muerte') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);

COMMIT;