SET NAMES UTF8;

INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-001' AND UPPER(TRIM(c.nombre)) = UPPER('Aborto') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-002' AND UPPER(TRIM(c.nombre)) = UPPER('Determinación de uso de drogas, fármacos o estupefacientes') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-003' AND UPPER(TRIM(c.nombre)) = UPPER('Edad cronológica') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-004' AND UPPER(TRIM(c.nombre)) = UPPER('Embarazo') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-005' AND UPPER(TRIM(c.nombre)) = UPPER('Embriaguez') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-006' AND UPPER(TRIM(c.nombre)) = UPPER('Enfermedad común') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-007' AND UPPER(TRIM(c.nombre)) = UPPER('Herida por arma blanca') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-008' AND UPPER(TRIM(c.nombre)) = UPPER('Herida por arma de fuego') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-009' AND UPPER(TRIM(c.nombre)) = UPPER('Intoxicación') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-010' AND UPPER(TRIM(c.nombre)) = UPPER('Lesiones') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-011' AND UPPER(TRIM(c.nombre)) = UPPER('Otros') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-012' AND UPPER(TRIM(c.nombre)) = UPPER('Reconocimiento médico para determinar estado de salud') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);
INSERT INTO delito_cometido (id_tipo_delito, id_clasificacion_delito) SELECT d.id_delito, c.id_clasificacion_delito FROM delito d JOIN clasificacion_delito c ON 1=1 WHERE d.codigo = 'MED-DEL-013' AND UPPER(TRIM(c.nombre)) = UPPER('Toma de muestras') AND NOT EXISTS (SELECT 1 FROM delito_cometido dc WHERE dc.id_tipo_delito = d.id_delito AND dc.id_clasificacion_delito = c.id_clasificacion_delito);

COMMIT;