SET NAMES UTF8;

INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Otras leyes | Otros títulos | Otros capítulos', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Otras leyes | Otros títulos | Otros capítulos'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra el patrimonio | Robo (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra el patrimonio | Robo (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra la vida y la integridad de la persona | Homicidios simples (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra la vida y la integridad de la persona | Homicidios simples (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra el patrimonio | De la extorsión y del chantaje (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra el patrimonio | De la extorsión y del chantaje (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra la vida y la integridad de la persona | Lesiones (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra la vida y la integridad de la persona | Lesiones (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley de Armas y Municiones | Otros títulos | De la portación (Ley de Armas y Munciones)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley de Armas y Municiones | Otros títulos | De la portación (Ley de Armas y Munciones)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley de Equipo Terminales Móviles | Otros títulos | Delitos, sanciones y prohibiciones (Ley de Equipos Terminales Móviles)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley de Equipo Terminales Móviles | Otros títulos | Delitos, sanciones y prohibiciones (Ley de Equipos Terminales Móviles)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra la vida y la integridad de la persona | Homicidios calificados (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra la vida y la integridad de la persona | Homicidios calificados (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra el patrimonio | Hurto (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra el patrimonio | Hurto (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley Contra la Narcoactividad | Otros títulos | De los delitos y de sus penas (Ley contra la Narcoactividad)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley Contra la Narcoactividad | Otros títulos | De los delitos y de sus penas (Ley contra la Narcoactividad)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra la libertad y seguridad de las personas | De los delitos contra la libertad individual (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra la libertad y seguridad de las personas | De los delitos contra la libertad individual (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley Contra el Lavado de Dinero u Otros Activos | Otros títulos | Del delito, de los responsables y de las penas (Ley Contra el Lavado de Dinero u', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley Contra el Lavado de Dinero u Otros Activos | Otros títulos | Del delito, de los responsables y de las penas (Ley Contra el Lavado de Dinero u'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra la administración de justicia | Del encubrimiento (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra la administración de justicia | Del encubrimiento (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra la libertad y seguridad de las personas | De las coacciones y amenazas (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra la libertad y seguridad de las personas | De las coacciones y amenazas (Código Penal)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley Contra la Delincuencia Organizada | Otros títulos | Delitos de la Delincuencia Organizada (Ley Contra la Delincuencia Organizada)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley Contra la Delincuencia Organizada | Otros títulos | Delitos de la Delincuencia Organizada (Ley Contra la Delincuencia Organizada)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley de Armas y Municiones | Otros títulos | Sobre la tenencia y transporte (Ley de Armas y Munciones)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley de Armas y Municiones | Otros títulos | Sobre la tenencia y transporte (Ley de Armas y Munciones)'));
INSERT INTO clasificacion_delito (codigo, nombre, descripcion, activo) SELECT NULL, 'Ley del Ramo Penal | De los delitos contra el patrimonio | De la estafa (Código Penal)', 'Fuente Sentenciados 2023', 1 FROM RDB$DATABASE WHERE NOT EXISTS (SELECT 1 FROM clasificacion_delito WHERE UPPER(TRIM(nombre)) = UPPER('Ley del Ramo Penal | De los delitos contra el patrimonio | De la estafa (Código Penal)'));

COMMIT;