-- Firebird DDL
-- Primera tranche del modelo: Denuncias registradas MP / VCM
-- Base para cargar la fuente del archivo: datos_base/Violencia/Violencia contra la mujer/Denuncias registradas/instrucciones.txt

SET SQL DIALECT 3;

CREATE TABLE continente (
    id_continente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE pais (
    id_pais INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_continente INTEGER NOT NULL,
    codigo VARCHAR(20),
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT fk_pais_continente FOREIGN KEY (id_continente) REFERENCES continente (id_continente)
);

CREATE TABLE departamento (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pais INTEGER NOT NULL,
    codigo VARCHAR(20),
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT fk_departamento_pais FOREIGN KEY (id_pais) REFERENCES pais (id_pais)
);

CREATE TABLE municipio (
    id_municipio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento INTEGER NOT NULL,
    codigo VARCHAR(20),
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT fk_municipio_departamento FOREIGN KEY (id_departamento) REFERENCES departamento (id_departamento)
);

CREATE TABLE area_geografica (
    id_area_geografica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE genero (
    id_genero INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE orientacion_sexual (
    id_orientacion_sexual INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE grupo_etnico (
    id_grupo_etnico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE estado_civil (
    id_estado_civil INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE condicion_alfabetica (
    id_condicion_alfabetica INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE nivel_escolaridad (
    id_nivel_escolaridad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    orden INTEGER
);

CREATE TABLE involucramiento (
    id_involucramiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE idioma_lengua (
    id_lengua INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    familia_linguistica VARCHAR(150)
);

CREATE TABLE tipo_hecho (
    id_tipo_hecho INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE tipo_institucion (
    id_tipo_institucion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE institucion_organicacion (
    id_institucion_organicacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_institucion VARCHAR(150) NOT NULL,
    id_tipo_institucion INTEGER NOT NULL,
    CONSTRAINT fk_institucion_tipo FOREIGN KEY (id_tipo_institucion) REFERENCES tipo_institucion (id_tipo_institucion)
);

CREATE TABLE clasificacion_delito (
    id_clasificacion_delito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30),
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(255),
    activo SMALLINT DEFAULT 1
);

CREATE TABLE delito (
    id_delito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30),
    nombre VARCHAR(150) NOT NULL,
    bien_juridico VARCHAR(150),
    activo SMALLINT DEFAULT 1
);

CREATE TABLE delito_cometido (
    id_delito_cometido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_delito INTEGER NOT NULL,
    id_clasificacion_delito INTEGER NOT NULL,
    CONSTRAINT fk_delito_cometido_delito FOREIGN KEY (id_tipo_delito) REFERENCES delito (id_delito),
    CONSTRAINT fk_delito_cometido_clasificacion FOREIGN KEY (id_clasificacion_delito) REFERENCES clasificacion_delito (id_clasificacion_delito)
);

CREATE TABLE tipo_residencia (
    id_tipo_residencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE ubicacion (
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_municipio INTEGER NOT NULL,
    id_area_geografica INTEGER,
    ciudad VARCHAR(120),
    zona VARCHAR(30),
    direccion_referencia VARCHAR(255),
    CONSTRAINT fk_ubicacion_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id_municipio),
    CONSTRAINT fk_ubicacion_area FOREIGN KEY (id_area_geografica) REFERENCES area_geografica (id_area_geografica)
);

CREATE TABLE persona (
    id_persona INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(150),
    apellidos VARCHAR(150),
    fecha_nacimiento DATE,
    cui VARCHAR(20),
    id_genero INTEGER,
    id_orientacion_sexual INTEGER,
    id_grupo_etnico INTEGER,
    id_estado_civil INTEGER,
    id_condicion_alfabetica INTEGER,
    id_nivel_escolaridad INTEGER,
    id_origen INTEGER,
    es_extranjero SMALLINT DEFAULT 0,
    CONSTRAINT fk_persona_genero FOREIGN KEY (id_genero) REFERENCES genero (id_genero),
    CONSTRAINT fk_persona_orientacion FOREIGN KEY (id_orientacion_sexual) REFERENCES orientacion_sexual (id_orientacion_sexual),
    CONSTRAINT fk_persona_grupo_etnico FOREIGN KEY (id_grupo_etnico) REFERENCES grupo_etnico (id_grupo_etnico),
    CONSTRAINT fk_persona_estado_civil FOREIGN KEY (id_estado_civil) REFERENCES estado_civil (id_estado_civil),
    CONSTRAINT fk_persona_condicion_alfabetica FOREIGN KEY (id_condicion_alfabetica) REFERENCES condicion_alfabetica (id_condicion_alfabetica),
    CONSTRAINT fk_persona_nivel_escolaridad FOREIGN KEY (id_nivel_escolaridad) REFERENCES nivel_escolaridad (id_nivel_escolaridad),
    CONSTRAINT fk_persona_origen FOREIGN KEY (id_origen) REFERENCES ubicacion (id_ubicacion)
);

CREATE TABLE idioma_persona (
    id_idioma_persona INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona INTEGER NOT NULL,
    id_lengua INTEGER NOT NULL,
    CONSTRAINT fk_idioma_persona_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona),
    CONSTRAINT fk_idioma_persona_lengua FOREIGN KEY (id_lengua) REFERENCES idioma_lengua (id_lengua)
);

CREATE TABLE hecho (
    id_hecho INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_hecho INTEGER NOT NULL,
    id_ubicacion INTEGER NOT NULL,
    fecha_hecho DATE,
    CONSTRAINT fk_hecho_tipo FOREIGN KEY (id_tipo_hecho) REFERENCES tipo_hecho (id_tipo_hecho),
    CONSTRAINT fk_hecho_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicacion (id_ubicacion)
);

CREATE TABLE involucrado_hecho (
    id_involucrado_hecho INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_involucrado INTEGER NOT NULL,
    id_tipo_involucramiento INTEGER NOT NULL,
    CONSTRAINT fk_involucrado_hecho_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_involucrado_hecho_persona FOREIGN KEY (id_involucrado) REFERENCES persona (id_persona),
    CONSTRAINT fk_involucrado_hecho_tipo FOREIGN KEY (id_tipo_involucramiento) REFERENCES involucramiento (id_involucramiento)
);

CREATE TABLE estado_denuncia (
    id_estado_denuncia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255),
    es_procesada SMALLINT DEFAULT 0
);

CREATE TABLE denuncia (
    id_denuncia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    fecha_denuncia DATE,
    id_estado_denuncia INTEGER NOT NULL,
    id_entididad_denuncia INTEGER,
    CONSTRAINT fk_denuncia_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_denuncia_estado FOREIGN KEY (id_estado_denuncia) REFERENCES estado_denuncia (id_estado_denuncia),
    CONSTRAINT fk_denuncia_institucion FOREIGN KEY (id_entididad_denuncia) REFERENCES institucion_organicacion (id_institucion_organicacion)
);

CREATE TABLE denuncia_estado_historial (
    id_denuncia_estado_historial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_denuncia INTEGER NOT NULL,
    id_estado_denuncia INTEGER NOT NULL,
    fecha_estado DATE,
    observaciones VARCHAR(255),
    CONSTRAINT fk_historial_denuncia FOREIGN KEY (id_denuncia) REFERENCES denuncia (id_denuncia),
    CONSTRAINT fk_historial_estado FOREIGN KEY (id_estado_denuncia) REFERENCES estado_denuncia (id_estado_denuncia)
);

CREATE TABLE clasificacion_evaluacion (
    id_clasificacion_evaluacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE evaluacion_medica_inacif (
    id_evaluacion_medica_inacif INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_persona INTEGER NOT NULL,
    id_clasificacion_evaluacion INTEGER NOT NULL,
    CONSTRAINT fk_evaluacion_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_evaluacion_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona),
    CONSTRAINT fk_evaluacion_clasificacion FOREIGN KEY (id_clasificacion_evaluacion) REFERENCES clasificacion_evaluacion (id_clasificacion_evaluacion)
);

CREATE TABLE exhumacion (
    id_exhumacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    CONSTRAINT fk_exhumacion_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho)
);

CREATE TABLE necropsia (
    id_necropsia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_persona INTEGER NOT NULL,
    causa_muerte VARCHAR(255),
    CONSTRAINT fk_necropsia_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_necropsia_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona)
);

CREATE TABLE tipo_fallo (
    id_tipo_fallo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE tipo_sentencia (
    id_tipo_sentencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE sentencia (
    id_sentencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_sentencia DATE,
    id_institucion_organicacion INTEGER,
    id_persona INTEGER,
    id_tipo_fallo INTEGER,
    id_delito INTEGER,
    id_involucramiento INTEGER,
    id_tipo_sentencia INTEGER,
    CONSTRAINT fk_sentencia_institucion FOREIGN KEY (id_institucion_organicacion) REFERENCES institucion_organicacion (id_institucion_organicacion),
    CONSTRAINT fk_sentencia_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona),
    CONSTRAINT fk_sentencia_fallo FOREIGN KEY (id_tipo_fallo) REFERENCES tipo_fallo (id_tipo_fallo),
    CONSTRAINT fk_sentencia_delito FOREIGN KEY (id_delito) REFERENCES delito (id_delito),
    CONSTRAINT fk_sentencia_involucramiento FOREIGN KEY (id_involucramiento) REFERENCES involucramiento (id_involucramiento),
    CONSTRAINT fk_sentencia_tipo FOREIGN KEY (id_tipo_sentencia) REFERENCES tipo_sentencia (id_tipo_sentencia)
);

CREATE TABLE sentencia_hecho (
    id_sentencia_hecho INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sentencia INTEGER NOT NULL,
    id_hecho INTEGER NOT NULL,
    CONSTRAINT fk_sentencia_hecho_sentencia FOREIGN KEY (id_sentencia) REFERENCES sentencia (id_sentencia),
    CONSTRAINT fk_sentencia_hecho_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho)
);

CREATE TABLE sede (
    id_sede INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_institucion_organicacion INTEGER,
    descripcion VARCHAR(255),
    id_ubicacion INTEGER,
    CONSTRAINT fk_sede_institucion FOREIGN KEY (id_institucion_organicacion) REFERENCES institucion_organicacion (id_institucion_organicacion),
    CONSTRAINT fk_sede_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicacion (id_ubicacion)
);

CREATE TABLE tipo_atencion (
    id_tipo_atencion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE atencion_victima (
    id_atencion_victima INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_sede INTEGER,
    id_victima INTEGER,
    id_tipo_delito_atendido INTEGER,
    id_atencion_brindada INTEGER,
    CONSTRAINT fk_atencion_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_atencion_sede FOREIGN KEY (id_sede) REFERENCES sede (id_sede),
    CONSTRAINT fk_atencion_victima_persona FOREIGN KEY (id_victima) REFERENCES persona (id_persona),
    CONSTRAINT fk_atencion_delito FOREIGN KEY (id_tipo_delito_atendido) REFERENCES delito (id_delito),
    CONSTRAINT fk_atencion_tipo FOREIGN KEY (id_atencion_brindada) REFERENCES tipo_atencion (id_tipo_atencion)
);

CREATE TABLE estado_caso (
    id_estado_caso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE caso_mp (
    id_caso_mp INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estado_caso INTEGER NOT NULL,
    id_delito_cometido INTEGER NOT NULL,
    CONSTRAINT fk_caso_mp_estado FOREIGN KEY (id_estado_caso) REFERENCES estado_caso (id_estado_caso),
    CONSTRAINT fk_caso_mp_delito_cometido FOREIGN KEY (id_delito_cometido) REFERENCES delito_cometido (id_delito_cometido)
);

CREATE TABLE medida_seguridad (
    id_medida_seguridad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_institucion_organicacion INTEGER,
    CONSTRAINT fk_medida_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_medida_institucion FOREIGN KEY (id_institucion_organicacion) REFERENCES institucion_organicacion (id_institucion_organicacion)
);

CREATE TABLE tipo_discriminacion (
    id_tipo_discriminacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE violencia_estructural (
    id_violencia_estructural INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_victima INTEGER NOT NULL,
    id_tipo_discriminacion INTEGER NOT NULL,
    CONSTRAINT fk_violencia_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_violencia_persona FOREIGN KEY (id_victima) REFERENCES persona (id_persona),
    CONSTRAINT fk_violencia_discriminacion FOREIGN KEY (id_tipo_discriminacion) REFERENCES tipo_discriminacion (id_tipo_discriminacion)
);

CREATE TABLE tipo_agresion_ninez (
    id_tipo_agresion_ninez INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE estado_escolarizacion (
    id_estado_escolarizacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255),
    es_escolarizado SMALLINT
);

CREATE TABLE sector_economico (
    id_sector_economico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE tipo_trabajo_infantil (
    id_tipo_trabajo_infantil INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE caso_violencia_ninez (
    id_caso_violencia_ninez INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_victima INTEGER NOT NULL,
    id_tipo_agresion_ninez INTEGER NOT NULL,
    id_estado_escolarizacion INTEGER,
    relacionado_trabajo_infantil SMALLINT,
    CONSTRAINT fk_caso_ninez_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_caso_ninez_victima FOREIGN KEY (id_victima) REFERENCES persona (id_persona),
    CONSTRAINT fk_caso_ninez_agresion FOREIGN KEY (id_tipo_agresion_ninez) REFERENCES tipo_agresion_ninez (id_tipo_agresion_ninez),
    CONSTRAINT fk_caso_ninez_escolarizacion FOREIGN KEY (id_estado_escolarizacion) REFERENCES estado_escolarizacion (id_estado_escolarizacion)
);

CREATE TABLE caso_ninez_trabajo_infantil (
    id_caso_ninez_trabajo_infantil INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caso_violencia_ninez INTEGER NOT NULL,
    id_sector_economico INTEGER,
    id_tipo_trabajo_infantil INTEGER,
    horas_semanales INTEGER,
    CONSTRAINT fk_caso_ninez_trabajo_caso FOREIGN KEY (id_caso_violencia_ninez) REFERENCES caso_violencia_ninez (id_caso_violencia_ninez),
    CONSTRAINT fk_caso_ninez_trabajo_sector FOREIGN KEY (id_sector_economico) REFERENCES sector_economico (id_sector_economico),
    CONSTRAINT fk_caso_ninez_trabajo_tipo FOREIGN KEY (id_tipo_trabajo_infantil) REFERENCES tipo_trabajo_infantil (id_tipo_trabajo_infantil)
);

CREATE TABLE embarazo_adolescente (
    id_embarazo_adolescente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_persona INTEGER NOT NULL,
    edad_gestante INTEGER,
    semana_gestacion INTEGER,
    CONSTRAINT fk_embarazo_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_embarazo_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona)
);

CREATE TABLE tipo_agresion_intrafamiliar (
    id_tipo_agresion_intrafamiliar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE tipo_medida_seguridad (
    id_tipo_medida_seguridad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE articulo_legal (
    id_articulo_legal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30),
    nombre VARCHAR(150) NOT NULL,
    ambito_legal VARCHAR(100),
    descripcion VARCHAR(255),
    activo SMALLINT DEFAULT 1
);

CREATE TABLE caso_violencia_intrafamiliar (
    id_caso_violencia_intrafamiliar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_boleta VARCHAR(50),
    id_hecho INTEGER NOT NULL,
    fecha_emision DATE,
    id_tipo_agresion_intrafamiliar INTEGER,
    id_victima INTEGER,
    id_agresor_principal INTEGER,
    quien_reporta VARCHAR(150),
    otras_victimas_total INTEGER,
    agresores_otros_total INTEGER,
    organismo_jurisdiccional VARCHAR(200),
    conducente VARCHAR(200),
    ley_aplicable VARCHAR(200),
    id_institucion_organicacion INTEGER,
    CONSTRAINT fk_caso_vif_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_caso_vif_agresion FOREIGN KEY (id_tipo_agresion_intrafamiliar) REFERENCES tipo_agresion_intrafamiliar (id_tipo_agresion_intrafamiliar),
    CONSTRAINT fk_caso_vif_victima FOREIGN KEY (id_victima) REFERENCES persona (id_persona),
    CONSTRAINT fk_caso_vif_agresor FOREIGN KEY (id_agresor_principal) REFERENCES persona (id_persona),
    CONSTRAINT fk_caso_vif_institucion FOREIGN KEY (id_institucion_organicacion) REFERENCES institucion_organicacion (id_institucion_organicacion)
);

CREATE TABLE caso_vif_articulo_legal (
    id_caso_vif_articulo_legal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caso_violencia_intrafamiliar INTEGER NOT NULL,
    id_articulo_legal INTEGER NOT NULL,
    CONSTRAINT fk_caso_vif_articulo_caso FOREIGN KEY (id_caso_violencia_intrafamiliar) REFERENCES caso_violencia_intrafamiliar (id_caso_violencia_intrafamiliar),
    CONSTRAINT fk_caso_vif_articulo_legal FOREIGN KEY (id_articulo_legal) REFERENCES articulo_legal (id_articulo_legal)
);

CREATE TABLE caso_vif_medida_seguridad (
    id_caso_vif_medida_seguridad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caso_violencia_intrafamiliar INTEGER NOT NULL,
    id_tipo_medida_seguridad INTEGER NOT NULL,
    CONSTRAINT fk_caso_vif_medida_caso FOREIGN KEY (id_caso_violencia_intrafamiliar) REFERENCES caso_violencia_intrafamiliar (id_caso_violencia_intrafamiliar),
    CONSTRAINT fk_caso_vif_medida_tipo FOREIGN KEY (id_tipo_medida_seguridad) REFERENCES tipo_medida_seguridad (id_tipo_medida_seguridad)
);

CREATE TABLE hogar (
    id_hogar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ubicacion INTEGER,
    tipo_hogar VARCHAR(120),
    descripcion VARCHAR(255),
    CONSTRAINT fk_hogar_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicacion (id_ubicacion)
);

CREATE TABLE persona_hogar (
    id_persona_hogar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona INTEGER NOT NULL,
    id_hogar INTEGER NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    parentesco_referencia VARCHAR(120),
    CONSTRAINT fk_persona_hogar_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona),
    CONSTRAINT fk_persona_hogar_hogar FOREIGN KEY (id_hogar) REFERENCES hogar (id_hogar)
);

CREATE TABLE caso_vif_hogar (
    id_caso_vif_hogar INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_caso_violencia_intrafamiliar INTEGER NOT NULL,
    id_hogar INTEGER NOT NULL,
    CONSTRAINT fk_caso_vif_hogar_caso FOREIGN KEY (id_caso_violencia_intrafamiliar) REFERENCES caso_violencia_intrafamiliar (id_caso_violencia_intrafamiliar),
    CONSTRAINT fk_caso_vif_hogar_hogar FOREIGN KEY (id_hogar) REFERENCES hogar (id_hogar)
);

CREATE TABLE fuente_salud (
    id_fuente_salud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE grupo_etario_salud (
    id_grupo_etario_salud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    orden INTEGER
);

CREATE TABLE denominador_poblacional (
    id_denominador_poblacional INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ubicacion INTEGER NOT NULL,
    anio_referencia INTEGER NOT NULL,
    id_grupo_etario_salud INTEGER,
    id_genero INTEGER,
    total_poblacion INTEGER,
    fuente VARCHAR(200),
    CONSTRAINT fk_denominador_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicacion (id_ubicacion),
    CONSTRAINT fk_denominador_grupo FOREIGN KEY (id_grupo_etario_salud) REFERENCES grupo_etario_salud (id_grupo_etario_salud),
    CONSTRAINT fk_denominador_genero FOREIGN KEY (id_genero) REFERENCES genero (id_genero)
);

CREATE TABLE condicion_salud (
    id_condicion_salud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_cie10 VARCHAR(20),
    nombre VARCHAR(120) NOT NULL
);

CREATE TABLE registro_salud (
    id_registro_salud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_fuente_salud INTEGER NOT NULL,
    id_ubicacion INTEGER NOT NULL,
    anio_registro INTEGER,
    id_grupo_etario_salud INTEGER,
    id_genero INTEGER,
    id_condicion_salud INTEGER,
    casos INTEGER,
    CONSTRAINT fk_registro_salud_fuente FOREIGN KEY (id_fuente_salud) REFERENCES fuente_salud (id_fuente_salud),
    CONSTRAINT fk_registro_salud_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicacion (id_ubicacion),
    CONSTRAINT fk_registro_salud_grupo FOREIGN KEY (id_grupo_etario_salud) REFERENCES grupo_etario_salud (id_grupo_etario_salud),
    CONSTRAINT fk_registro_salud_genero FOREIGN KEY (id_genero) REFERENCES genero (id_genero),
    CONSTRAINT fk_registro_salud_condicion FOREIGN KEY (id_condicion_salud) REFERENCES condicion_salud (id_condicion_salud)
);
