-- Parche de catalogos faltantes para alinear DB con analisis.md

CREATE TABLE tipo_falta (
    id_tipo_falta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30),
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(255),
    activo SMALLINT DEFAULT 1
);

CREATE TABLE estado_ebriedad (
    id_estado_ebriedad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255)
);

CREATE TABLE clasificacion_ocupacion (
    id_clasificacion_ocupacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30),
    nombre VARCHAR(255) NOT NULL,
    nivel_clasificacion INTEGER,
    descripcion VARCHAR(255)
);
