-- Tabla transaccional faltante en DB segun modelo analisis.md

CREATE TABLE falta (
    id_falta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_tipo_falta INTEGER NOT NULL,
    CONSTRAINT fk_falta_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_falta_tipo FOREIGN KEY (id_tipo_falta) REFERENCES tipo_falta (id_tipo_falta)
);
