-- Tabla transaccional faltante en DB segun modelo analisis.md

CREATE TABLE hecho_delictivo (
    id_hecho_delictivo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hecho INTEGER NOT NULL,
    id_delito INTEGER NOT NULL,
    CONSTRAINT fk_hecho_delictivo_hecho FOREIGN KEY (id_hecho) REFERENCES hecho (id_hecho),
    CONSTRAINT fk_hecho_delictivo_delito FOREIGN KEY (id_delito) REFERENCES delito_cometido (id_delito_cometido)
);
