SET NAMES UTF8;

/*
  Soporte incremental para ocupaciones segun analisis actualizado:
  - ocupacion_clasificacion
  - ocupacion
  - persona_ocupacion
*/

SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATIONS
      WHERE TRIM(RDB$RELATION_NAME) = 'OCUPACION_CLASIFICACION'
  )) THEN
    EXECUTE STATEMENT '
      CREATE TABLE ocupacion_clasificacion (
        id_ocupacion_clasificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_clasificacion VARCHAR(150) NOT NULL,
        observaciones VARCHAR(255)
      )
    ';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATIONS
      WHERE TRIM(RDB$RELATION_NAME) = 'OCUPACION'
  )) THEN
    EXECUTE STATEMENT '
      CREATE TABLE ocupacion (
        id_ocupacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_ocupacion VARCHAR(180) NOT NULL,
        descripcion VARCHAR(255),
        id_ocupacion_clasificacion INTEGER,
        CONSTRAINT fk_ocupacion_clasificacion FOREIGN KEY (id_ocupacion_clasificacion)
          REFERENCES ocupacion_clasificacion (id_ocupacion_clasificacion)
      )
    ';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$RELATIONS
      WHERE TRIM(RDB$RELATION_NAME) = 'PERSONA_OCUPACION'
  )) THEN
    EXECUTE STATEMENT '
      CREATE TABLE persona_ocupacion (
        id_persona_ocupacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_persona INTEGER NOT NULL,
        id_ocupacion INTEGER NOT NULL,
        fecha_inicio DATE,
        fecha_fin DATE,
        fuente VARCHAR(150),
        CONSTRAINT fk_persona_ocupacion_persona FOREIGN KEY (id_persona)
          REFERENCES persona (id_persona),
        CONSTRAINT fk_persona_ocupacion_ocupacion FOREIGN KEY (id_ocupacion)
          REFERENCES ocupacion (id_ocupacion)
      )
    ';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = 'IDX_OCUPACION_CLASIF'
  )) THEN
    EXECUTE STATEMENT 'CREATE INDEX idx_ocupacion_clasif ON ocupacion (id_ocupacion_clasificacion)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = 'IDX_PEROCUP_PERSONA'
  )) THEN
    EXECUTE STATEMENT 'CREATE INDEX idx_perocup_persona ON persona_ocupacion (id_persona)';
END^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1 FROM RDB$INDICES WHERE TRIM(RDB$INDEX_NAME) = 'IDX_PEROCUP_OCUPACION'
  )) THEN
    EXECUTE STATEMENT 'CREATE INDEX idx_perocup_ocupacion ON persona_ocupacion (id_ocupacion)';
END^

SET TERM ; ^

COMMIT;
