SET NAMES UTF8;

-- Staging table for Agraviados set-based loading
-- Run once per environment/database.

CREATE TABLE stg_agraviados (
    id_stg BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INTEGER NOT NULL,
    batch_num INTEGER NOT NULL,
    source_num_corre INTEGER,
    pcode VARCHAR(40) NOT NULL,
    nombres VARCHAR(120) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    fecha_nacimiento DATE,
    fecha_hecho DATE,
    depto_nombre VARCHAR(120),
    muni_nombre VARCHAR(120),
    zona VARCHAR(30),
    sexo_nombre VARCHAR(40),
    estado_civil_nombre VARCHAR(60),
    delito_nombre VARCHAR(150),
    clasificacion_nombre VARCHAR(150),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_stg_agr_run ON stg_agraviados(run_id);
CREATE INDEX idx_stg_agr_run_pcode ON stg_agraviados(run_id, pcode);
CREATE INDEX idx_stg_agr_run_loc ON stg_agraviados(run_id, depto_nombre, muni_nombre, zona);
CREATE INDEX idx_stg_agr_run_hecho ON stg_agraviados(run_id, fecha_hecho);

COMMIT;
