SET NAMES UTF8;
SET TERM ^;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (
      SELECT 1
      FROM rdb$indices
      WHERE TRIM(rdb$index_name) = 'IDX_PERSONA_NOMBRES_APELLIDOS'
  )) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_PERSONA_NOMBRES_APELLIDOS ON PERSONA (NOMBRES, APELLIDOS)';
END^

SET TERM ;^

COMMIT;